"""empty message

Revision ID: ee0b10243811
Revises: 24dfd71dfe4d
Create Date: 2025-11-12 21:21:13.418416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee0b10243811'
down_revision: Union[str, None] = '24dfd71dfe4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_cache',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('cache_type', sa.String(length=50), nullable=False),
    sa.Column('text_preview', sa.String(length=1000), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.Column('use_count', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_cache_key', 'llm_cache', ['cache_key'], unique=True)
    op.create_index('idx_llm_cache_last_used', 'llm_cache', ['last_used_at'], unique=False)
    op.create_index('idx_llm_cache_type', 'llm_cache', ['cache_type'], unique=False)
    op.create_index(op.f('ix_llm_cache_cache_key'), 'llm_cache', ['cache_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_cache_cache_key'), table_name='llm_cache')
    op.drop_index('idx_llm_cache_type', table_name='llm_cache')
    op.drop_index('idx_llm_cache_last_used', table_name='llm_cache')
    op.drop_index('idx_llm_cache_key', table_name='llm_cache')
    op.drop_table('llm_cache')
    # ### end Alembic commands ###

